"use client";

import { useEffect, useState } from "react";
import {
  collection,
  limit,
  onSnapshot,
  orderBy,
  query,
  where,
} from "firebase/firestore";
import { Award } from "lucide-react";
import { db } from "@/lib/firestore";
import { useAuth } from "@/lib/auth-context";
import { formatXof } from "@/lib/format";
import type { Commission } from "@/lib/types";
import { Badge, EmptyState, Spinner, StatCard, TableShell, Td, Th } from "@/components/ui";

export default function CommissionsPage() {
  const { fbUser, profile } = useAuth();
  const [rows, setRows] = useState<Commission[] | null>(null);

  useEffect(() => {
    if (!fbUser) return;
    const q = query(
      collection(db, "commissions"),
      where("agentId", "==", fbUser.uid),
      orderBy("periodDate", "desc"),
      limit(100)
    );
    return onSnapshot(q, (snap) => {
      setRows(snap.docs.map((d) => ({ id: d.id, ...d.data() }) as Commission));
    });
  }, [fbUser]);

  return (
    <div>
      <h1 className="mb-1 text-xl font-bold">My Commissions</h1>
      <p className="mb-6 text-sm text-slate-400">
        You earn a percentage of the GGR (bets minus wins) generated by your customers, credited
        automatically every day.
      </p>

      <div className="mb-6 max-w-xs">
        <StatCard
          label="Total Earned"
          value={formatXof(profile?.stats?.commissionEarned ?? 0)}
          hint="lifetime commission"
          icon={<Award size={20} />}
        />
      </div>

      {!rows ? (
        <Spinner />
      ) : rows.length === 0 ? (
        <EmptyState message="No commissions yet — they appear after your customers play." />
      ) : (
        <TableShell>
          <thead>
            <tr>
              <Th>Date</Th>
              <Th>Customer</Th>
              <Th>GGR</Th>
              <Th>Rate</Th>
              <Th>Commission</Th>
              <Th>Status</Th>
            </tr>
          </thead>
          <tbody>
            {rows.map((c) => (
              <tr key={c.id}>
                <Td className="tabular-nums">{c.periodDate}</Td>
                <Td>{c.playerName ?? c.playerId.slice(0, 8)}</Td>
                <Td className="tabular-nums">{formatXof(c.ggrAmount)}</Td>
                <Td className="tabular-nums">{(c.commissionRate * 100).toFixed(1)}%</Td>
                <Td className="font-semibold tabular-nums text-emerald-400">
                  {formatXof(c.commissionAmount)}
                </Td>
                <Td>
                  <Badge value={c.paidAt ? "paid" : "pending"} />
                </Td>
              </tr>
            ))}
          </tbody>
        </TableShell>
      )}
    </div>
  );
}
