"use client";

import { useState } from "react";
import toast from "react-hot-toast";
import { Copy, Users, UserCog, Banknote, TrendingUp, Award, WalletCards } from "lucide-react";
import { useAuth } from "@/lib/auth-context";
import { formatXof } from "@/lib/format";
import { Card, StatCard } from "@/components/ui";

const SITE = process.env.NEXT_PUBLIC_SITE_URL ?? "https://beteseaviator.com";

export default function AgentDashboard() {
  const { profile, wallet } = useAuth();
  const [copied, setCopied] = useState(false);

  const stats = profile?.stats ?? {};
  const ggr = (stats.totalBets ?? 0) - (stats.totalWins ?? 0);
  const referralLink = `${SITE}/register?ref=${profile?.agentSlug ?? ""}`;

  async function copyLink() {
    await navigator.clipboard.writeText(referralLink);
    setCopied(true);
    toast.success("Referral link copied!");
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div>
      <h1 className="mb-1 text-xl font-bold">Welcome back, {profile?.name}</h1>
      <p className="mb-6 text-sm text-slate-400">
        Share your link, bring in players, earn commission on the profit they generate.
      </p>

      <Card className="mb-6 border-emerald-500/30 bg-emerald-500/5">
        <p className="mb-2 text-xs uppercase tracking-widest text-emerald-300">
          Your referral link
        </p>
        <div className="flex flex-col gap-2 sm:flex-row sm:items-center">
          <code className="flex-1 overflow-x-auto rounded-lg bg-slate-950/70 px-3 py-2 text-sm text-emerald-200">
            {referralLink}
          </code>
          <button
            onClick={copyLink}
            className="flex items-center justify-center gap-1.5 rounded-lg bg-emerald-500 px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-emerald-400"
          >
            <Copy size={15} /> {copied ? "Copied!" : "Copy"}
          </button>
        </div>
        <p className="mt-2 text-xs text-slate-500">
          Every customer who signs up through this link is permanently attached to you.
        </p>
      </Card>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <StatCard
          label="My Customers"
          value={stats.customerCount ?? 0}
          hint="players from your link"
          icon={<Users size={20} />}
        />
        {profile?.role === "super_agent" && (
          <StatCard
            label="Sub Agents"
            value={stats.subAgentCount ?? 0}
            hint="agents working under you"
            icon={<UserCog size={20} />}
          />
        )}
        <StatCard
          label="Customer Deposits"
          value={formatXof(stats.customerDeposits ?? 0)}
          hint="total deposited by your customers"
          icon={<Banknote size={20} />}
        />
        <StatCard
          label="Sales (GGR)"
          value={formatXof(Math.max(0, ggr))}
          hint="profit generated by your customers"
          icon={<TrendingUp size={20} />}
        />
        <StatCard
          label="Commission Earned"
          value={formatXof(stats.commissionEarned ?? 0)}
          hint="lifetime commission credited"
          icon={<Award size={20} />}
        />
        <StatCard
          label="Commission Due"
          value={formatXof(wallet?.balance ?? 0)}
          hint="available to withdraw now"
          icon={<WalletCards size={20} />}
        />
      </div>
    </div>
  );
}
