"use client";

import { Users, UserCog, Banknote, TrendingUp, Award, WalletCards } from "lucide-react";
import { useAuth } from "@/lib/auth-context";
import { formatXof } from "@/lib/format";
import { AgentMarketingLinks } from "@/components/agent/AgentMarketingLinks";
import { Card, StatCard } from "@/components/ui";

export default function AgentDashboard() {
  const { profile, wallet } = useAuth();
  const stats = profile?.stats ?? {};
  const ggr = (stats.totalBets ?? 0) - (stats.totalWins ?? 0);

  return (
    <div>
      <h1 className="mb-1 text-xl font-bold">Welcome back, {profile?.name}</h1>
      <p className="mb-6 text-sm text-slate-400">
        Share your agent link or subdomain — every customer who signs up is attached to you for
        commission.
      </p>

      {profile?.agentSlug ? (
        <div className="mb-6">
          <AgentMarketingLinks slug={profile.agentSlug} agentName={profile.name} />
        </div>
      ) : (
        <Card className="mb-6 border-amber-500/30 bg-amber-500/10 text-sm text-amber-100">
          Your agent username is not set yet. Contact BETESE admin to assign one — your marketing
          link is created automatically from your username.
        </Card>
      )}

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <StatCard
          label="My Customers"
          value={stats.customerCount ?? 0}
          hint="players from your link"
          icon={<Users size={20} />}
        />
        {profile?.role === "super_agent" && (
          <StatCard
            label="Sub Agents"
            value={stats.subAgentCount ?? 0}
            hint="agents working under you"
            icon={<UserCog size={20} />}
          />
        )}
        <StatCard
          label="Customer Deposits"
          value={formatXof(stats.customerDeposits ?? 0)}
          hint="total deposited by your customers"
          icon={<Banknote size={20} />}
        />
        <StatCard
          label="Sales (GGR)"
          value={formatXof(Math.max(0, ggr))}
          hint="profit generated by your customers"
          icon={<TrendingUp size={20} />}
        />
        <StatCard
          label="Commission Earned"
          value={formatXof(stats.commissionEarned ?? 0)}
          hint="lifetime commission credited"
          icon={<Award size={20} />}
        />
        <StatCard
          label="Commission Due"
          value={formatXof(wallet?.balance ?? 0)}
          hint="available to withdraw now"
          icon={<WalletCards size={20} />}
        />
      </div>
    </div>
  );
}
