/** @deprecated Import from ./phone instead */
export {
  GAMBIA_COUNTRY_CODE,
  GAMBIA_LOCAL_LENGTH,
  GAMBIA_PHONE_HINT,
  PHONE_HINT,
  PHONE_LABEL,
  PHONE_PLACEHOLDER,
  PHONE_COUNTRY_OPTIONS,
  getPhoneCountryMeta,
  isActivePhoneCountry,
  formatGambiaPhoneLocal,
  formatPhoneDisplay,
  normalizeGambiaPhone,
  normalizeGambiaPhoneLocal,
  normalizePhone,
  normalizePhoneE164,
  normalizePhoneLocal,
  phoneToEmail,
  type ParsedPhone,
  type PhoneCountry,
} from "./phone";
