/** @deprecated Import from ./phone instead */
export {
  GAMBIA_COUNTRY_CODE,
  GAMBIA_LOCAL_LENGTH,
  GAMBIA_PHONE_HINT,
  PHONE_HINT,
  WAVE_PHONE_HINT,
  PHONE_LABEL,
  PHONE_PLACEHOLDER,
  PHONE_COUNTRY_OPTIONS,
  getPhoneCountryMeta,
  isActivePhoneCountry,
  formatGambiaPhoneLocal,
  formatPhoneDisplay,
  normalizeGambiaPhone,
  normalizeGambiaPhoneLocal,
  normalizePhone,
  normalizePhoneE164,
  normalizePhoneLocal,
  sanitizePhoneInput,
  toWaveAccountNumber,
  phoneToEmail,
  phoneAuthEmails,
  phoneStorageKeys,
  type ParsedPhone,
  type PhoneCountry,
} from "./phone";
export { classifyGambia9, gambia9Canonical, gambia9WaveNumber, type Gambia9Plan } from "./gambia9";
