/** Curated QTech game IDs — keep in sync with functions/src/gameCatalog.ts */
const QTECH_LOBBY_GAME_IDS = new Set<string>([
  "AVX-aviatrix",
  "AVX-secondchance",
  "BLC-crash",
  "BTL-chickenrun",
  "BTV-plinko",
  "EVP-uncrossablerush",
  "GZX-pilot",
  "IOG-chickenroad",
  "IOG-chickenroad2",
  "IOG-chickenroad2bonus",
  "IOG-chickenroadbonus",
  "IOG-chickenroadgold",
  "IOG-chickenroadice",
  "IOG-chickenroadrace",
  "IOG-chickenroadvegas",
  "IOG-chickenvszombies",
  "IOG-coinflip",
  "IOG-cricketroad",
  "IOG-jumper",
  "IOG-limbo",
  "IOG-mines",
  "IOG-rabbitroad",
  "IOG-rockpaperscissors",
  "IOG-stairs",
  "IOG-tower",
  "IOG-triple",
  "IOG-twist",
  "IOG-twistsanquentin",
  "IOG-twistxmas",
  "KAG-goldenbull",
  "PPC-chicken",
  "SMS-cricketx",
  "SMS-footballx",
  "SMS-jetx",
  "SMS-plinkox",
  "SMS-rollx",
  "SPB-aviator",
  "SPB-balloon",
  "SPB-dice",
  "SPB-hilo",
  "SPB-hotline",
  "SPB-mines",
  "SPB-pilotchicken",
  "SPB-plinko",
  "SPB-trader",
  "UPG-dice",
  "UPG-hilo",
  "UPG-mines",
  "UPG-plinko",
]);

export function isCatalogQTechGameId(qtechGameId: string): boolean {
  return QTECH_LOBBY_GAME_IDS.has(qtechGameId.trim());
}
